spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:apiTestDb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
    springframework:
      cache: DEBUG
    com:
    currency:
      convert: DEBUG

cache:
  ttl-seconds: 5