spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:convertDb;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driverClassName: org.h2.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  paths-to-match: /admin/manage/*
  show-actuator: false
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - url: currency-convert-api.yaml
        name: currency-convert-api
    urls-primary-name: currency-convert-api


currencyLayer:
  url: https://api.currencylayer.com

rate:
  limit:
    capacity: 100
    days: 1

