openapi: 3.0.3
info:
  title: Currency Convert API
  description: This API converts currency from one to another.
  version: 1.0.0
  contact:
    name: Ognyan Ignatov
    email: 0g0ignatov@gmail.com
servers:
  - url: 'http://localhost:8080'
    description: Local server
  - url: 'https://api.example.com'
    description: Production server
paths:
  /convert:
    get:
      summary: Convert currency
      description: Convert currency from one to another.
      operationId: getConvertedCurrency
      parameters:
        - in: query
          schema:
            type: string
            enum:
              - AED
              - AFN
              - ALL
              - AMD
              - ANG
              - AOA
              - ARS
              - AUD
              - AWG
              - AZN
              - BAM
              - BBD
              - BDT
              - BGN
              - BHD
              - BIF
              - BMD
              - BND
              - BOB
              - BRL
              - BSD
              - BTC
              - BTN
              - BWP
              - BYR
              - BZD
              - CAD
              - CDF
              - CHF
              - CLF
              - CLP
              - CNY
              - COP
              - CRC
              - CUC
              - CUP
              - CVE
              - CZK
              - DJF
              - DKK
              - DOP
              - DZD
              - EGP
              - ERN
              - ETB
              - EUR
              - FJD
              - FKP
              - GBP
              - GEL
              - GGP
              - GHS
              - GIP
              - GMD
              - GNF
              - GTQ
              - GYD
              - HKD
              - HNL
              - HRK
              - HTG
              - HUF
              - IDR
              - ILS
              - IMP
              - INR
              - IQD
              - IRR
              - ISK
              - JEP
              - JMD
              - JOD
              - JPY
              - KES
              - KGS
              - KHR
              - KMF
              - KPW
              - KRW
              - KWD
              - KYD
              - KZT
              - LAK
              - LBP
              - LKR
              - LRD
              - LSL
              - LTL
              - LVL
              - LYD
              - MAD
              - MDL
              - MGA
              - MKD
              - MMK
              - MNT
              - MOP
              - MRO
              - MUR
              - MVR
              - MWK
              - MXN
              - MYR
              - MZN
              - NAD
              - NGN
              - NIO
              - NOK
              - NPR
              - NZD
              - OMR
              - PAB
              - PEN
              - PGK
              - PHP
              - PKR
              - PLN
              - PYG
              - QAR
              - RON
              - RSD
              - RUB
              - RWF
              - SAR
              - SBD
              - SCR
              - SDG
              - SEK
              - SGD
              - SHP
              - SLL
              - SOS
              - SRD
              - STD
              - SVC
              - SYP
              - SZL
              - THB
              - TJS
              - TMT
              - TND
              - TOP
              - TRY
              - TTD
              - TWD
              - TZS
              - UAH
              - UGX
              - USD
              - UYU
              - UZS
              - VEF
              - VND
              - VUV
              - WST
              - XAF
              - XAG
              - XAU
              - XCD
              - XDR
              - XOF
              - XPF
              - YER
              - ZAR
              - ZMK
              - ZMW
              - ZWL
          name: sourceCurrencyCode
          description: The currency to convert from.
          required: true
        - name: targetCurrencyCode
          in: query
          description: The currency to convert to.
          required: true
          schema:
            type: string
            enum:
              - AED
              - AFN
              - ALL
              - AMD
              - ANG
              - AOA
              - ARS
              - AUD
              - AWG
              - AZN
              - BAM
              - BBD
              - BDT
              - BGN
              - BHD
              - BIF
              - BMD
              - BND
              - BOB
              - BRL
              - BSD
              - BTC
              - BTN
              - BWP
              - BYR
              - BZD
              - CAD
              - CDF
              - CHF
              - CLF
              - CLP
              - CNY
              - COP
              - CRC
              - CUC
              - CUP
              - CVE
              - CZK
              - DJF
              - DKK
              - DOP
              - DZD
              - EGP
              - ERN
              - ETB
              - EUR
              - FJD
              - FKP
              - GBP
              - GEL
              - GGP
              - GHS
              - GIP
              - GMD
              - GNF
              - GTQ
              - GYD
              - HKD
              - HNL
              - HRK
              - HTG
              - HUF
              - IDR
              - ILS
              - IMP
              - INR
              - IQD
              - IRR
              - ISK
              - JEP
              - JMD
              - JOD
              - JPY
              - KES
              - KGS
              - KHR
              - KMF
              - KPW
              - KRW
              - KWD
              - KYD
              - KZT
              - LAK
              - LBP
              - LKR
              - LRD
              - LSL
              - LTL
              - LVL
              - LYD
              - MAD
              - MDL
              - MGA
              - MKD
              - MMK
              - MNT
              - MOP
              - MRO
              - MUR
              - MVR
              - MWK
              - MXN
              - MYR
              - MZN
              - NAD
              - NGN
              - NIO
              - NOK
              - NPR
              - NZD
              - OMR
              - PAB
              - PEN
              - PGK
              - PHP
              - PKR
              - PLN
              - PYG
              - QAR
              - RON
              - RSD
              - RUB
              - RWF
              - SAR
              - SBD
              - SCR
              - SDG
              - SEK
              - SGD
              - SHP
              - SLL
              - SOS
              - SRD
              - STD
              - SVC
              - SYP
              - SZL
              - THB
              - TJS
              - TMT
              - TND
              - TOP
              - TRY
              - TTD
              - TWD
              - TZS
              - UAH
              - UGX
              - USD
              - UYU
              - UZS
              - VEF
              - VND
              - VUV
              - WST
              - XAF
              - XAG
              - XAU
              - XCD
              - XDR
              - XOF
              - XPF
              - YER
              - ZAR
              - ZMK
              - ZMW
              - ZWL
        - name: amount
          in: query
          description: The amount to convert.
          required: true
          schema:
            type: number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertedCurrency'
      tags:
        - Currency Convert
components:
  schemas:
    ConvertedCurrency:
      title: ConvertedCurrency
      x-stoplight:
        id: pykaliogqh3i9
      type: object
      properties:
        transactionId:
          type: string
          x-stoplight:
            id: ycahmw8wr8g24
        currencyCode:
          type: string
          enum:
              - AED
              - AFN
              - ALL
              - AMD
              - ANG
              - AOA
              - ARS
              - AUD
              - AWG
              - AZN
              - BAM
              - BBD
              - BDT
              - BGN
              - BHD
              - BIF
              - BMD
              - BND
              - BOB
              - BRL
              - BSD
              - BTC
              - BTN
              - BWP
              - BYR
              - BZD
              - CAD
              - CDF
              - CHF
              - CLF
              - CLP
              - CNY
              - COP
              - CRC
              - CUC
              - CUP
              - CVE
              - CZK
              - DJF
              - DKK
              - DOP
              - DZD
              - EGP
              - ERN
              - ETB
              - EUR
              - FJD
              - FKP
              - GBP
              - GEL
              - GGP
              - GHS
              - GIP
              - GMD
              - GNF
              - GTQ
              - GYD
              - HKD
              - HNL
              - HRK
              - HTG
              - HUF
              - IDR
              - ILS
              - IMP
              - INR
              - IQD
              - IRR
              - ISK
              - JEP
              - JMD
              - JOD
              - JPY
              - KES
              - KGS
              - KHR
              - KMF
              - KPW
              - KRW
              - KWD
              - KYD
              - KZT
              - LAK
              - LBP
              - LKR
              - LRD
              - LSL
              - LTL
              - LVL
              - LYD
              - MAD
              - MDL
              - MGA
              - MKD
              - MMK
              - MNT
              - MOP
              - MRO
              - MUR
              - MVR
              - MWK
              - MXN
              - MYR
              - MZN
              - NAD
              - NGN
              - NIO
              - NOK
              - NPR
              - NZD
              - OMR
              - PAB
              - PEN
              - PGK
              - PHP
              - PKR
              - PLN
              - PYG
              - QAR
              - RON
              - RSD
              - RUB
              - RWF
              - SAR
              - SBD
              - SCR
              - SDG
              - SEK
              - SGD
              - SHP
              - SLL
              - SOS
              - SRD
              - STD
              - SVC
              - SYP
              - SZL
              - THB
              - TJS
              - TMT
              - TND
              - TOP
              - TRY
              - TTD
              - TWD
              - TZS
              - UAH
              - UGX
              - USD
              - UYU
              - UZS
              - VEF
              - VND
              - VUV
              - WST
              - XAF
              - XAG
              - XAU
              - XCD
              - XDR
              - XOF
              - XPF
              - YER
              - ZAR
              - ZMK
              - ZMW
              - ZWL
          x-stoplight:
            id: nf1pjwtcqparl
        amount:
          type: number
          x-stoplight:
            id: iaqac52u2du5c
          format: double
  parameters: {}
tags:
  - name: Currency Convert
